[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "yash-fetch"
authors = [{name = "Yash Singh", email = "yash9vardhan@gmail.com"}]
readme = "README.md"
license = {file = "LICENSE"}
requires-python = ">=3.0"
dynamic = ["version", "description"]
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
  "Development Status :: 5 - Production/Stable",
  "Environment :: Console"
]
dependencies = ["beautifulsoup4", "requests"]

[project.urls]
Home = "https://github.com/yashsinghcodes/fetch"

[project.scripts]
fetch = "fetch.fetch:arguments"

[project.optional-dependencies]
dev = ["flit"]

[tool.flit.module]
name = "fetch"
